#Levantar un servicio de bd con mysql

#Imagen base
FROM mysql:9.1.0

#Variables de entorno
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=prueba
ENV MYSQL_USER=prueba
ENV MYSQL_PASSWORD=prueba

#Puerto 
EXPOSE 3306